function plot1(optionsCell,table)
%% Plotting methodVar_objectiveFix_solverFix_FeasibilityTolFix

colors_solid = {'k','b','r'};
colors_solid_marker = {'ok','ob','or'};
colors_dotted = {'k--','b--','r--'};
colors_dotted_marker = {'sk','sb','sr'};
%% plotting rho distribution
figure()
hold on;

for i=1:3

plot([4 5 6 7,8],[table.rho_max(5*(i-1)+1)...
    table.rho_max(5*(i-1)+2) table.rho_max(5*(i-1)+3)...
    table.rho_max(5*(i-1)+4) table.rho_max(5*(i-1)+5)],...
    colors_solid{i},'linewidth',1.5);
marker = plot([4 5 6 7,8],[table.rho_max(5*(i-1)+1)...
    table.rho_max(5*(i-1)+2) table.rho_max(5*(i-1)+3)...
    table.rho_max(5*(i-1)+4) table.rho_max(5*(i-1)+5)],...
    colors_solid_marker{i},'MarkerSize',10,'linewidth',1.5);
set(get(get(marker,'Annotation'),'LegendInformation'),...
    'IconDisplayStyle','off');
plot([4 5 6 7,8],[table.rho_ave(5*(i-1)+1)...
    table.rho_ave(5*(i-1)+2) table.rho_ave(5*(i-1)+3)...
    table.rho_ave(5*(i-1)+4) table.rho_ave(5*(i-1)+5)],...
    colors_dotted{i},'linewidth',1.5);     
markerh = plot([4 5 6 7,8],[table.rho_ave(5*(i-1)+1)...
    table.rho_ave(5*(i-1)+2) table.rho_ave(5*(i-1)+3)...
    table.rho_ave(5*(i-1)+4) table.rho_ave(5*(i-1)+5)],...
    colors_dotted_marker{i},'MarkerSize',10,'linewidth',1.5);
set(get(get(markerh,'Annotation'),'LegendInformation'),...
'IconDisplayStyle','off');

axis([3 9 0 0.25])
ylabel('\rho_{opt}')
xlabel('degee of multiplier')
xticks([3,4,5,6,7,8]);
xticklabels({'3','4','5','6','7','8','9'});
legendInfo{2*(i-1)+1} = [num2str(i) '-S-Procedure OPT'];
legendInfo{2*(i-1)+2} = [num2str(i) '-S-Procedure AVE'];

end

legend(legendInfo,'Position',[0.1 0.1 0.2 0.3]);

[~,string] = optionsByCounter(optionsCell{1});
name = strcat('method',string.solver_method,...
        string.FeasibilityTol,string.objective);
filename = strcat(pwd,'/plots/',name,'.tex');
matlab2tikz('filename',filename,'showInfo', false);

%% plot feasibility
figure()
hold on;

for i=1:3

plot([4 5 6 7 8],[table.feasibility_analytical(5*(i-1)+1)...
    table.feasibility_analytical(5*(i-1)+2) ...
    table.feasibility_analytical(5*(i-1)+3)...
    table.feasibility_analytical(5*(i-1)+4)...
    table.feasibility_analytical(5*(i-1)+5)],...
    colors_solid{i},'linewidth',1.5,'DisplayName', 'test1');
marker = plot([4 5 6 7 8],[table.feasibility_analytical(5*(i-1)+1)...
    table.feasibility_analytical(5*(i-1)+2) ...
    table.feasibility_analytical(5*(i-1)+3)...
    table.feasibility_analytical(5*(i-1)+4)...
    table.feasibility_analytical(5*(i-1)+5)],...
    colors_solid_marker{i},'MarkerSize',10,'linewidth',1.5);
set(get(get(marker,'Annotation'),'LegendInformation'),...
    'IconDisplayStyle','off');

plot([4 5 6 7 8],[table.feasibility_numerical(5*(i-1)+1)...
    table.feasibility_numerical(5*(i-1)+2) ...
    table.feasibility_numerical(5*(i-1)+3)...
    table.feasibility_numerical(5*(i-1)+4)...
    table.feasibility_numerical(5*(i-1)+5)],...
    colors_dotted{i},'linewidth',1.5);
markerh = plot([4 5 6 7 8],[table.feasibility_numerical(5*(i-1)+1)...
    table.feasibility_numerical(5*(i-1)+2) ...
    table.feasibility_numerical(5*(i-1)+3)...
    table.feasibility_numerical(5*(i-1)+4)...
    table.feasibility_numerical(5*(i-1)+5)],...
    colors_dotted_marker{i},'MarkerSize',10,'linewidth',1.5);
set(get(get(markerh,'Annotation'),'LegendInformation'),...
    'IconDisplayStyle','off');

axis([3 9 0 100])
ylabel('Feasibility [%]')
xlabel('degee of multiplier []')
xticks([3,4,5,6,7,8,9]);
xticklabels({'3','4','5','6','7','8','9'});

legendInfo{2*(i-1)+1} = [num2str(i) '-S-Procedure ana'];
legendInfo{2*(i-1)+2} = [num2str(i) '-S-Procedure num'];

end

legend(legendInfo,'Position',[0.1 0.1 0.2 0.3]);

[~,string] = optionsByCounter(optionsCell{1});
name = strcat('methodFeasibility',string.solver_method,...
        string.FeasibilityTol,string.objective);
filename = strcat(pwd,'/plots/',name,'.tex');
matlab2tikz('filename',filename,'showInfo', false);

end

